# Copyright 2020 The MediaPipe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//mediapipe/framework:encode_binary_proto.bzl", "encode_binary_proto")

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

# `.pngblob` is used instead of `.png` to prevent iOS build from preprocessing the image.
# OpenCV is unable to read a PNG file preprocessed by the iOS build.
exports_files(["1.pngblob",
	       "2.pngblob",
	       "3.pngblob",
	       "4.pngblob",
	       "5.pngblob",    
	       "6.pngblob", 
	       "7.pngblob",    
	       "8.pngblob",    
	       "9.pngblob",    
	       "10.pngblob",    
	       "11.pngblob",    
	       "12.pngblob",    
	       "13.pngblob",    
	       "14.pngblob",    
	       "15.pngblob",    
	       "16.pngblob",    
	       "17.pngblob",    
	       "18.pngblob"])

